MANIFEST:   'data/master_index.yml'
INPUTZIP:   '/Users/westgard/Desktop/original_inventories.zip'
SOURCEDIR:  '/Users/westgard/Box Sync/DPI Projects/DigitalPreservation/aws_migration/data/'
TARGETDIR:  '/Users/westgard/Box Sync/DPI Projects/DigitalPreservation/aws_migration/data/restored_inventories'
